# Actual implementation for Heroku

name: A deployment pipeline to Heroku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: $${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          justlogin: true
          docker_options: "--no-cache"
          process_type: web


# Below are the examples from this chapter
# name: Release DevOps with Docker

# on:
#   push:
#     branches: 
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Login to DockerHub
#       uses: docker/login-action@v1 
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME  }}
#         password: ${{ secrets.DOCKERHUB_TOKEN  }}
    
#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: ruikawahara/coursepage:latest
